# Generated by Django 2.0.1 on 2019-11-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='User',
            new_name='user',
        ),
    ]
